apps/notes/urls.py
from django.urls import path

from . import views

app_name = "notes"

urlpatterns = [
    path("list/", views.NotesListView.as_view(), name="notes_list"),
    path("listkey/", views.SecretKeyListView.as_view(), name="secretkey_list"),
    #
    #    path("delete/", views.delete_contacts_view, name="contacts_delete"),
    path("delete/<int:pk>/", views.NoteDeleteView.as_view(), name="notes_delete"),
    path("deletekey/<int:pk>/", views.SecretKeyDeleteView.as_view(), name="secretkey_delete"),
    #
    path("edit/<int:pk>/", views.NoteEditView.as_view(), name="notes_edit"),
    path("editkey/<int:pk>/", views.SecretKeyEditView.as_view(), name="secretkey_edit"),
    # path("keysecret/<int:pk>/", views.SecretKeyEditView.as_view(), name="secretkey_edit"),
    #
    #    path("generate/", views.generate_contacts_view, name="contacts_generate"),
    #
    # path("create/", views.NoteCreateView.as_view(), name="notes_create"),
    path("createsecret/", views.note_create_form_view, name="notes_createview"),
    path("viewsecret/<int:pk>", views.NoteSecretView.as_view(), name="notes_secretview"),
    #
    path("createkey/", views.SecretKeyCreateView.as_view(), name="secretkey_create"),
    #    path("detail/<int:pk>/", views.ContactDetailView.as_view(), name="contacts_detail"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.base.urls")),
    path("notes/", include("apps.notes.urls")),
]

apps/notes/models/note.py
from django.db import models


class Note(models.Model):
    text_in = models.CharField(max_length=1000)
    text_out = models.CharField(max_length=1000)

    # passkey = models.CharField(max_length=100)

    passkey = models.ForeignKey(
        "SecretKey",
        related_name="passkey",
        on_delete=models.CASCADE,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        blank=False,
        null=False,
    )

    modified_at = models.DateTimeField(
        auto_now=True,
        blank=False,
        null=False,
    )

    def __str__(self):
        return f"{self.text_out} {self.created_at} {self.modified_at}"

    class Meta:
        ordering = ["-modified_at", "text_in"]

apps/notes/models/secretkey.py
from django.db import models


class SecretKey(models.Model):
    value = models.CharField(max_length=100)

    created_at = models.DateTimeField(
        auto_now_add=True,
        blank=False,
        null=False,
    )

    modified_at = models.DateTimeField(
        auto_now=True,
        blank=False,
        null=False,
    )

    def __str__(self) -> str:
        return self.value

    __repr__ = __str__

apps/notes/forms.py
from django import forms

from apps.notes.models import Note, SecretKey


class NoteForm(forms.Form):
    text_in = forms.CharField(
        label="Text (in)",
        required=True,
    )

    passkey = forms.ModelChoiceField(
        queryset=SecretKey.objects.all(),
        label="passkey",
        required=True,
    )

    class Meta:
        model = Note

        fieldsets = ("text_in", "passkey")


class NoteSecretForm(forms.ModelForm):
    # text_in = forms.CharField(
    #     label="Text (in)",
    #     required=True,
    # )
    #
    # passkey = forms.ModelChoiceField(
    #     queryset=SecretKey.objects.all(),
    #     label="passkey",
    #     required=True,
    # )

    class Meta:
        model = Note

        fields = ("text_in", "passkey")

apps/notes/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, FormView
from django.shortcuts import render

from apps.notes.forms import NoteForm, NoteSecretForm
from apps.notes.models import Note, SecretKey
from apps.services.save_note import save_note
from apps.services.secret import get_encrypt_decrypt_string


class NotesListView(ListView):
    model = Note


class SecretKeyListView(ListView):
    model = SecretKey


class NoteCreateView(CreateView):
    model = Note
    fields = ["text_in", "passkey"]

    success_url = reverse_lazy("notes:notes_list")


class SecretKeyCreateView(CreateView):
    model = SecretKey
    fields = ["value"]
    success_url = reverse_lazy("notes:secretkey_list")


class NoteDeleteView(DeleteView):
    model = Note
    success_url = reverse_lazy("notes:notes_list")


class SecretKeyDeleteView(DeleteView):
    model = SecretKey
    success_url = reverse_lazy("notes:secretkey_list")


class NoteEditView(UpdateView):
    model = Note
    fields = (
        "text_in",
        "passkey",
    )

    def get_success_url(self):
        # return reverse_lazy("contacts:contacts_update", kwargs=dict(pk=self.kwargs["pk"]))
        return reverse_lazy("notes:notes_list")


class SecretKeyEditView(UpdateView):
    model = SecretKey
    fields = ("value",)

    def get_success_url(self):
        # return reverse_lazy("contacts:contacts_update", kwargs=dict(pk=self.kwargs["pk"]))
        return reverse_lazy("notes:secretkey_list")


def note_create_form_view(request):
    if request.method == "POST":
        form = NoteForm(request.POST)

        if form.is_valid():
            text_in = form.cleaned_data["text_in"]
            passkey_pk = form.cleaned_data["passkey"].pk
            save_note(text_in=text_in, passkey_pk=passkey_pk)
            needed_html = "notes/note_list.html"
        else:
            needed_html = "notes/note_form.html"

    else:
        form = NoteForm()
        needed_html = "notes/note_form.html"

    return render(
        request=request,
        template_name=needed_html,
        context=dict(
            notes_list=Note.objects.all(),
            form=form,
        ),
    )


def note_secret_form_view(request, pk):
    if request.method == "POST":
        form = NoteSecretForm(request.POST)

        if form.is_valid():
            #    text_in = form.cleaned_data["text_in"]
            #    passkey_pk = form.cleaned_data["passkey"].pk
            #    save_note(text_in=text_in, passkey_pk=passkey_pk)
            needed_html = "notes/note_list.html"
        else:
            needed_html = "notes/notesecret_form.html"

    else:
        form = NoteForm()
        needed_html = "notes/notesecret_form.html"

    return render(
        request=request,
        template_name=needed_html,
        context=dict(
            notes_list=Note.objects.all(),
            form=form,
        ),
    )


class NoteSecretView(FormView):
    model = Note
    form_class = NoteSecretForm
    template_name = "notes/notesecret_form.html"

    def get_success_url(self):
        return reverse_lazy("notes:notes_secretview", kwargs=dict(pk=self.kwargs["pk"]))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = Note.objects.get(pk=self.kwargs["pk"])
        passkey = kwargs["instance"].passkey
        text_out = kwargs["instance"].text_out
        kwargs["instance"].text_in = get_encrypt_decrypt_string(text_out, passkey.value, mode="decrypt", debug=False)
        return kwargs

    # def form_valid(self, form):
    #    form.save()
    #    return super().form_valid(form)

apps/templates/notes/_note_list_base.html
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col"></th>
        <!--
        <th>Text (in) </th>
        -->
        <th>Passkey</th>
        <th>Text (out)</th>
        <th>Created at</th>
        <th>Modified at</th>

    </tr>
    </thead>
    {% for note in object_list %}
        <tr>
            <th scope="row"></th>

            <!--
            <td>{{ note.text_in }}</td>
            -->
            <td>{{ note.passkey }}</td>
            <td>{{ note.text_out }}</td>
            <td>{{ note.created_at }}</td>
            <td>{{ note.modified_at }}</td>

            <td>
                <a href="{% url 'notes:notes_secretview' note.pk %}">
                    <button class="btn btn-outline-primary" type="button">
                        View
                    </button>
                </a>
            </td>

            <td>
                <a href="{% url 'notes:notes_delete' note.pk %}">
                    <button class="btn btn-outline-danger" type="button">
                        Delete
                    </button>
                </a>
            </td>



        </tr>
    {% endfor %}
</table>

apps/templates/notes/_note_navbar.html
<nav class="navbar navbar-light bg-light">
    <form class="container-fluid justify-content-start">

        <a href="{% url 'notes:notes_list' %}">
            <button class="btn btn-outline-primary" type="button">
                List of Notes
            </button>
        </a>

        <a href="{% url 'notes:notes_createview' %}">
            <button class="btn btn-outline-secondary" type="button">
                Add Note
            </button>
        </a>

        <a href="{% url 'notes:secretkey_list' %}">
            <button class="btn btn-outline-primary" type="button">
                List of pass keys
            </button>
        </a>

        <a href="{% url 'notes:secretkey_create' %}">
            <button class="btn btn-outline-secondary" type="button">
                Add pass key
            </button>
        </a>

    </form>
</nav>

apps/templates/notes/_secretkey_list_base.html
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col"></th>
        <th>Passkey</th>
        <th>Created at</th>
        <th>Modified at</th>

    </tr>
    </thead>
    {% for key in object_list %}
        <tr>
            <th scope="row"></th>

            <td>{{ key.value }}</td>
            <td>{{ key.created_at }}</td>
            <td>{{ key.modified_at }}</td>

            <td>
                <a href="{% url 'notes:secretkey_edit' key.pk %}">
                    <button class="btn btn-outline-primary" type="button">
                        Edit
                    </button>
                </a>
            </td>

            <td>
                <a href="{% url 'notes:secretkey_delete' key.pk %}">
                    <button class="btn btn-outline-danger" type="button">
                        Delete
                    </button>
                </a>
            </td>

        </tr>
    {% endfor %}
</table>

apps/templates/notes/note_confirm_delete.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>"Are you sure you want to delete <b>{{ object }}</b> ?"</p>
        {{ form }}
        <div>

            <button class="btn btn-outline-danger" type="submit">Delete</button>

            <a href="{% url 'notes:notes_list' %}">
                <button class="btn btn-outline-primary" type="button">
                    Cancel
                </button>
            </a>

        </div>
    </form>

{% endblock %}

apps/templates/notes/note_form.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1> New note </h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <div>

            <button class="btn btn-outline-danger" type="submit">Save</button>

            <a href="{% url 'notes:notes_list' %}">
                <button class="btn btn-outline-primary" type="button">
                    Cancel
                </button>
            </a>

        </div>
    </form>

{% endblock %}

apps/templates/notes/note_list.html
{% extends "_helpers/_base.html" %}

<div>
{% block content %}

    {% include "notes/_note_navbar.html" %}

    <h1>Notes</h1>

    {% include "notes/_note_list_base.html" with notes_list=object_list %}
{% endblock %}
</div>

apps/templates/notes/notesecret_form.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1> View Note </h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <div>

            <!--
            <button class="btn btn-outline-danger" type="submit">Return</button>
            -->

            <a href="{% url 'notes:notes_list' %}">
                <button class="btn btn-outline-primary" type="button">
                    Return
                </button>
            </a>

        </div>
    </form>

{% endblock %}

apps/templates/notes/secretkey_confirm_delete.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>"Are you sure you want to delete <b>{{ object }}</b> ?"</p>
        {{ form }}
        <div>

            <button class="btn btn-outline-danger" type="submit">Delete</button>

            <a href="{% url 'notes:secretkey_list' %}">
                <button class="btn btn-outline-primary" type="button">
                    Cancel
                </button>
            </a>

        </div>
    </form>

{% endblock %}

apps/templates/notes/secretkey_form.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1> New pass key </h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <div>

            <button class="btn btn-outline-danger" type="submit">Save</button>

            <a href="{% url 'notes:secretkey_list' %}">
                <button class="btn btn-outline-primary" type="button">
                    Cancel
                </button>
            </a>

        </div>
    </form>

{% endblock %}

apps/templates/notes/secretkey_list.html
{% extends "_helpers/_base.html" %}

<div>
{% block content %}

    {% include "notes/_note_navbar.html" %}

    <h1>Pass Keys</h1>

    {% include "notes/_secretkey_list_base.html" with secretkey_list=object_list %}
{% endblock %}
</div>