apps/base/urls.py
from django.urls import path
from apps.base import views


app_name = "base"

urlpatterns = [
    path("", views.home_page, name="home_page"),
    path("aboutus/", views.about_us_page, name="about_us_page"),
    path("contacts/", views.contacts_page, name="contacts_page"),
]

apps/notes/urls.py
from django.urls import path

from . import views

app_name = "notes"

urlpatterns = [
    path("list/", views.NotesListView.as_view(), name="notes_list"),
    path("listkey/", views.SecretKeyListView.as_view(), name="secretkey_list"),
    #
    #    path("delete/", views.delete_contacts_view, name="contacts_delete"),
    path("delete/<int:pk>/", views.NoteDeleteView.as_view(), name="notes_delete"),
    path("deletekey/<int:pk>/", views.SecretKeyDeleteView.as_view(), name="secretkey_delete"),
    #
    path("edit/<int:pk>/", views.NoteEditView.as_view(), name="notes_edit"),
    path("editkey/<int:pk>/", views.SecretKeyEditView.as_view(), name="secretkey_edit"),
    # path("keysecret/<int:pk>/", views.SecretKeyEditView.as_view(), name="secretkey_edit"),
    #
    #    path("generate/", views.generate_contacts_view, name="contacts_generate"),
    #
    # path("create/", views.NoteCreateView.as_view(), name="notes_create"),
    path("createsecret/", views.note_create_form_view, name="notes_createview"),
    path("viewsecret/<int:pk>", views.NoteSecretView.as_view(), name="notes_secretview"),
    #
    path("createkey/", views.SecretKeyCreateView.as_view(), name="secretkey_create"),
    #    path("detail/<int:pk>/", views.ContactDetailView.as_view(), name="contacts_detail"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.base.urls")),
    path("notes/", include("apps.notes.urls")),
]

apps/base/views.py
import datetime

from django.shortcuts import render


def home_page(request):
    now = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M:%S")

    return render(
        request=request,
        template_name="base/home_page.html",
        context={
            "greetings_text": f"Hi, now is {now} in UTC.",
            "title": "Django base project",
        },
    )


def about_us_page(request):
    # now = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M:%S")
    text_for_page = "Short description about us"
    return render(
        request=request,
        template_name="base/about_us_page.html",
        context={
            "text_for_page": f"{text_for_page}",
            "title": "About us",
        },
    )


def contacts_page(request):
    # now = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M:%S")
    text_for_page = (
        "Our contacts:" "  phone number: 212121212" "  email: tyruetyurey@erithyreuiyt" "  address: stree F, 4587 City"
    )

    return render(
        request=request,
        template_name="base/contacts_page.html",
        context={
            "text_for_page": f"{text_for_page}",
            "title": "Our contacts",
        },
    )

apps/templates/_helpers/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {% if title %}
                {{ title }}
            {% else %}
                Welcome!
            {% endif %}
            | My Django base Website
        {% endblock %}
    </title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
{% include "_helpers/_header.html" %}

<div>
    {% block content %}
        <h1>Hello!</h1>
    {% endblock %}
</div>

</body>
</html>

apps/templates/_helpers/_header.html
<header>
    <div class="container">
        {% load static %}

        <div>
            <img src="{% static 'logo/django_base_project.png' %}" width="1301" height="41"
                 alt="Django base project logo">
        </div>

        <nav class="navbar navbar-expand navbar-dark bg-dark" aria-label="Second navbar example">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"> </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarsExample02">
                    <ul class="navbar-nav me-auto">
                        <!--
                        <li class="nav-item">

                            <a class="navbar-brand" href="{% url 'base:home_page' %}">
                                <img src="{% static 'logo/logo_cs_ico.ico' %}" alt="Logo" width="30" height="24"
                                     class="d-inline-block align-text-top">
                                Home
                            </a>
                        </li>
                        -->
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'base:home_page' %}">
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'base:about_us_page' %}">
                                About us
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'notes:notes_list' %}">
                                Notes
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">
                                Admin
                            </a>
                        </li>
                    </ul>
                    <form>
                        <input class="form-control" type="text" placeholder="Search" aria-label="Search">
                    </form>
                </div>
            </div>
        </nav>
    </div>
    <br>
</header>